export const classOptions = {
  label: "Class",
  options: {
    barbarian: {
      label: "Barbarian",
      default_ability_score: {
        str: 15,
        dex: 13,
        con: 14,
        int: 10,
        wis: 12,
        cha: 8,
      },
      subclasses: [
        "Path of the Berserker",
        "Path of the Wild Heart",
        "Path of the World Tree",
        "Path of the Zealot",
      ],
    },
    bard: {
      label: "Bard",
      default_ability_score: {
        str: 8,
        dex: 14,
        con: 12,
        int: 13,
        wis: 10,
        cha: 15,
      },
      subclasses: [
        "College of Dance",
        "College of Glamour",
        "College of Lore",
        "College of Valor",
      ],
    },
    cleric: {
      label: "Cleric",
      default_ability_score: {
        str: 14,
        dex: 8,
        con: 13,
        int: 10,
        wis: 15,
        cha: 12,
      },
      subclasses: [
        "Life Domain",
        "Light Domain",
        "Trickery Domain",
        "War Domain",
      ],
    },
    druid: {
      label: "Druid",
      default_ability_score: {
        str: 8,
        dex: 12,
        con: 14,
        int: 13,
        wis: 15,
        cha: 10,
      },
      subclasses: [
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of the Sea",
        "Circle of the Stars",
      ],
    },
    fighter: {
      label: "Fighter",
      default_ability_score: {
        str: 15,
        dex: 14,
        con: 13,
        int: 8,
        wis: 10,
        cha: 12,
      },
      subclasses: [
        "Battle Master",
        "Champion",
        "Eldritch Knight",
        "Psi Warrior",
      ],
    },
    monk: {
      label: "Monk",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 10,
        wis: 14,
        cha: 8,
      },
      subclasses: [
        "Warrior of Mercy",
        "Warrior of Shadow",
        "Warrior of the Elements",
        "Warrior of the Open Hand",
      ],
    },
    paladin: {
      label: "Paladin",
      default_ability_score: {
        str: 15,
        dex: 10,
        con: 13,
        int: 8,
        wis: 12,
        cha: 14,
      },
      subclasses: [
        "Oath of Devotion",
        "Oath of Glory",
        "Oath of the Ancients",
        "Oath of Vengeance",
      ],
    },
    ranger: {
      label: "Ranger",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 8,
        wis: 14,
        cha: 10,
      },
      subclasses: ["Beast Master", "Fey Wanderer", "Gloom Stalker", "Hunter"],
    },
    rogue: {
      label: "Rogue",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 14,
        wis: 10,
        cha: 8,
      },
      subclasses: ["Arcane Trickster", "Assassin", "Soulknife", "Thief"],
    },
    sorcerer: {
      label: "Sorcerer",
      default_ability_score: {
        str: 10,
        dex: 13,
        con: 14,
        int: 8,
        wis: 12,
        cha: 15,
      },
      subclasses: [
        "Aberrant Sorcery",
        "Clockwork Sorcery",
        "Draconic Sorcery",
        "Wild Magic Sorcery",
      ],
    },
    warlock: {
      label: "Warlock",
      default_ability_score: {
        str: 8,
        dex: 14,
        con: 13,
        int: 12,
        wis: 10,
        cha: 15,
      },
      subclasses: [
        "Archfey Patron",
        "Celestial Patron",
        "Fiend Patron",
        "Great Old One Patron",
      ],
    },
    wizard: {
      label: "Wizard",
      default_ability_score: {
        str: 8,
        dex: 12,
        con: 13,
        int: 15,
        wis: 14,
        cha: 10,
      },
      subclasses: ["Abjurer", "Diviner", "Evoker", "Illusionist"],
    },
  },
};
