export const classOptions = {
  label: "Class",
  options: {
    barbarian: {
      label: "Barbarian",
      default_ability_score: {
        str: 15,
        dex: 13,
        con: 14,
        int: 10,
        wis: 12,
        cha: 8,
      },
      subclasses: [
        "Path of the Berserker",
        "Path of the Wild Heart",
        "Path of the World Tree",
        "Path of the Zealot",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Animal Handling",
          "Athletics",
          "Intimidation",
          "Nature",
          "Perception",
          "Survival",
        ],
      },
    },
    bard: {
      label: "Bard",
      default_ability_score: {
        str: 8,
        dex: 14,
        con: 12,
        int: 13,
        wis: 10,
        cha: 15,
      },
      subclasses: [
        "College of Dance",
        "College of Glamour",
        "College of Lore",
        "College of Valor",
      ],
      skill_proficiencies: {
        choose: 3,
        options: "any",
      },
      spellcasting: {
        type: "full",
        cantripsKnown: {
          1: 2,
          4: 3,
          10: 4,
        },
      },
    },
    cleric: {
      label: "Cleric",
      default_ability_score: {
        str: 14,
        dex: 8,
        con: 13,
        int: 10,
        wis: 15,
        cha: 12,
      },
      subclasses: [
        "Life Domain",
        "Light Domain",
        "Trickery Domain",
        "War Domain",
      ],
      skill_proficiencies: {
        choose: 2,
        options: ["History", "Insight", "Medicine", "Persuasion", "Religion"],
      },
      spellcasting: {
        type: "full",
        cantripsKnown: {
          1: 3,
          4: 4,
          10: 5,
        },
      },
    },
    druid: {
      label: "Druid",
      default_ability_score: {
        str: 8,
        dex: 12,
        con: 14,
        int: 13,
        wis: 15,
        cha: 10,
      },
      subclasses: [
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of the Sea",
        "Circle of the Stars",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Arcana",
          "Animal Handling",
          "Insight",
          "Medicine",
          "Nature",
          "Perception",
          "Religion",
          "Survival",
        ],
      },
      spellcasting: {
        type: "full",
        cantripsKnown: {
          1: 2,
          4: 3,
          10: 4,
        },
      },
    },
    fighter: {
      label: "Fighter",
      default_ability_score: {
        str: 15,
        dex: 14,
        con: 13,
        int: 8,
        wis: 10,
        cha: 12,
      },
      subclasses: [
        "Battle Master",
        "Champion",
        "Eldritch Knight",
        "Psi Warrior",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Acrobatics",
          "Animal Handling",
          "Athletics",
          "History",
          "Insight",
          "Intimidation",
          "Perception",
          "Survival",
        ],
      },
      subclass_spellcasting: {
        "Eldritch Knight": {
          type: "third",
          spellListClass: "Wizard",
          minLevel: 3,
          cantripsKnown: {
            3: 2,
            10: 3,
          },
        },
      },
    },
    monk: {
      label: "Monk",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 10,
        wis: 14,
        cha: 8,
      },
      subclasses: [
        "Warrior of Mercy",
        "Warrior of Shadow",
        "Warrior of the Elements",
        "Warrior of the Open Hand",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Acrobatics",
          "Athletics",
          "History",
          "Insight",
          "Religion",
          "Stealth",
        ],
      },
    },
    paladin: {
      label: "Paladin",
      default_ability_score: {
        str: 15,
        dex: 10,
        con: 13,
        int: 8,
        wis: 12,
        cha: 14,
      },
      subclasses: [
        "Oath of Devotion",
        "Oath of Glory",
        "Oath of the Ancients",
        "Oath of Vengeance",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Athletics",
          "Insight",
          "Intimidation",
          "Medicine",
          "Persuasion",
          "Religion",
        ],
      },
      spellcasting: {
        type: "half",
        minLevel: 2,
      },
    },
    ranger: {
      label: "Ranger",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 8,
        wis: 14,
        cha: 10,
      },
      subclasses: ["Beast Master", "Fey Wanderer", "Gloom Stalker", "Hunter"],
      skill_proficiencies: {
        choose: 3,
        options: [
          "Animal Handling",
          "Athletics",
          "Insight",
          "Investigation",
          "Nature",
          "Perception",
          "Stealth",
          "Survival",
        ],
      },
      spellcasting: {
        type: "half",
        minLevel: 2,
      },
    },
    rogue: {
      label: "Rogue",
      default_ability_score: {
        str: 12,
        dex: 15,
        con: 13,
        int: 14,
        wis: 10,
        cha: 8,
      },
      subclasses: ["Arcane Trickster", "Assassin", "Soulknife", "Thief"],
      skill_proficiencies: {
        choose: 4,
        options: [
          "Acrobatics",
          "Athletics",
          "Deception",
          "Insight",
          "Intimidation",
          "Investigation",
          "Perception",
          "Performance",
          "Persuasion",
          "Sleight of Hand",
          "Stealth",
        ],
      },
      subclass_spellcasting: {
        "Arcane Trickster": {
          type: "third",
          spellListClass: "Wizard",
          minLevel: 3,
          cantripsKnown: {
            3: 3,
            10: 4,
          },
        },
      },
    },
    sorcerer: {
      label: "Sorcerer",
      default_ability_score: {
        str: 10,
        dex: 13,
        con: 14,
        int: 8,
        wis: 12,
        cha: 15,
      },
      subclasses: [
        "Aberrant Sorcery",
        "Clockwork Sorcery",
        "Draconic Sorcery",
        "Wild Magic Sorcery",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Arcana",
          "Deception",
          "Insight",
          "Intimidation",
          "Persuasion",
          "Religion",
        ],
      },
      spellcasting: {
        type: "full",
        cantripsKnown: {
          1: 4,
          4: 5,
          10: 6,
        },
      },
    },
    warlock: {
      label: "Warlock",
      default_ability_score: {
        str: 8,
        dex: 14,
        con: 13,
        int: 12,
        wis: 10,
        cha: 15,
      },
      subclasses: [
        "Archfey Patron",
        "Celestial Patron",
        "Fiend Patron",
        "Great Old One Patron",
      ],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Arcana",
          "Deception",
          "History",
          "Intimidation",
          "Investigation",
          "Nature",
          "Religion",
        ],
      },
      spellcasting: {
        type: "pact",
        cantripsKnown: {
          1: 2,
          4: 3,
          10: 4,
        },
      },
    },
    wizard: {
      label: "Wizard",
      default_ability_score: {
        str: 8,
        dex: 12,
        con: 13,
        int: 15,
        wis: 14,
        cha: 10,
      },
      subclasses: ["Abjurer", "Diviner", "Evoker", "Illusionist"],
      skill_proficiencies: {
        choose: 2,
        options: [
          "Arcana",
          "History",
          "Insight",
          "Investigation",
          "Medicine",
          "Religion",
        ],
      },
      spellcasting: {
        type: "full",
        cantripsKnown: {
          1: 3,
          4: 4,
          10: 5,
        },
      },
    },
  },
};

